// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare global {
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface Window {
    electronAPI?: {
      vault: {
        getFiles: () => Promise<import("./types").VaultItem[]>;
        getPath: () => Promise<string>;
        setPath: (newPath: string) => Promise<boolean>;
        readFile: (filePath: string) => Promise<string>;
        writeFile: (filePath: string, content: string) => Promise<void>;
        createFile: (filePath: string) => Promise<boolean>;
        createFolder: (folderPath: string) => Promise<boolean>;
        renameItem: (itemPath: string, newName: string) => Promise<string | boolean>;
        deleteItem: (itemPath: string) => Promise<boolean>;
        openFolder: () => Promise<boolean>;
        getGitState: () => Promise<{ initialized: boolean }>;
        initGit: () => Promise<
          { success: true; initialized: boolean } | { success: false; initialized: boolean; error: string }
        >;
        commitGit: (message: string) => Promise<{ success: true } | { success: false; error: string }>;
      };
    };
  }
}

export {};
